name: Go Build for Linux

on:
  push:
    branches:
      - "main"
      - "gitActionTest"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libx11-dev \
            libxi-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libxext-dev \
            libxfixes-dev \
            pkg-config

      - name: Tidy Go modules
        run: go mod tidy

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next tag
        id: get_tag
        run: |
          latest=$(git tag --list 't1.0.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest"
          if [ -z "$latest" ]; then
            next_tag="t1.0.0"
          else
            minor=$(echo "$latest" | awk -F. '{print $3}')
            next_minor=$((minor + 1))
            next_tag="t1.0.$next_minor"
          fi
          echo "tag=$next_tag" >> $GITHUB_OUTPUT
          echo "Next tag will be: $next_tag"

      - name: Create and push tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}

      - name: Build binary
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/myproject-linux-amd64 ./entry

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
