name: Go Build and Place in Builds Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      # Step 3: Install native dependencies for OpenGL and GLFW
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libx11-dev \
            libxi-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libxext-dev \
            libxfixes-dev \
            pkg-config

      # Step 4: Ensure the 'builds' directory exists
      - name: Ensure /builds directory exists
        run: mkdir -p builds

      # Step 5: Build the Go project
      - name: Build Go project
        run: go build -o builds/myproject ./cmd/gopad
