name: Go Build for Linux

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Install system deps (Linux only)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libx11-dev \
            libxi-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libxext-dev \
            libxfixes-dev \
            pkg-config

      - name: Tidy modules
        run: go mod tidy

      - name: Build binary for Linux
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/myproject-linux-amd64 ./entry

      - name: Create and push a tag
        run: |
          # Create a version tag with 'T' for test version followed by date and time
          TAG_NAME="vT$(date +'%Y%m%d%H%M%S')"

          # Create the tag locally with a message
          git tag -a $TAG_NAME -m "Release version $TAG_NAME"

          # Push the tag to GitHub
          git push origin $TAG_NAME

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
